# Generated by Django 2.2.5 on 2019-10-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileerpAccounts',
        ),
        migrations.DeleteModel(
            name='MobileerpEmployees',
        ),
    ]
