# Generated by Django 2.2.5 on 2019-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20191016_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acct_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_type', models.CharField(blank=True, choices=[('ADMIN', 'administrator'), ('STD', 'standard')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'Account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('addr1', models.CharField(blank=True, max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('addr1', models.CharField(blank=True, max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_dt', models.DateTimeField()),
                ('pay_type', models.CharField(blank=True, choices=[('CA', 'Cash'), ('CR', 'Credit')], max_length=10, null=True)),
                ('invoice_num', models.IntegerField()),
            ],
            options={
                'db_table': 'Invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_dt', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('C', 'Complete'), ('P', 'Pending')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
