# Generated by Django 2.2.5 on 2019-11-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_auto_20191102_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
