# Generated by Django 2.2.5 on 2019-11-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0006_auto_20191102_0438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False, 'ordering': ['acct_type']},
        ),
        migrations.CreateModel(
            name='EmpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp.Employee')),
            ],
        ),
    ]
