# Generated by Django 2.2.5 on 2019-11-02 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0007_auto_20191102_0442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpUser',
            new_name='ErpUser',
        ),
        migrations.AlterModelTable(
            name='erpuser',
            table='ErpUser',
        ),
    ]
