# Generated by Django 2.2.5 on 2019-11-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20191102_0444'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterModelOptions(
            name='erpuser',
            options={'managed': False},
        ),
    ]
