# Generated by Django 2.2.5 on 2019-11-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_auto_20191106_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Order_Details',
                'managed': False,
            },
        ),
    ]
