# Generated by Django 2.2.5 on 2019-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'Order_Detail',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['lname', 'fname', 'cust_id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'ordering': ['title', 'lname', 'fname', 'emp_id'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='erpuser',
            options={'managed': False, 'verbose_name': 'ERP User', 'verbose_name_plural': 'ERP Users'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False, 'ordering': ['make', 'model'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': False, 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ['status', 'order_id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
