# Generated by Django 2.2.5 on 2019-11-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20191111_0340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='OrderDetail',
        ),
    ]
